import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import * as ctrl from "../controllers/notification.controller.js";
const router=Router();
router.use(requireAuth);
router.get("/",ctrl.list);
router.get("/unread-count",ctrl.unreadCount);
router.patch("/read-all",ctrl.readAll);
router.patch("/:id/read",ctrl.read);
export default router;
